const express = require('express');
const Contribution = require('../models/Contribution');
const Pool = require('../models/Pool');
const { auth } = require('../middleware/authMiddleware');

const router = express.Router();

// POST /api/contributions — join a pool
router.post('/', auth, async (req, res) => {
  try {
    const { poolId } = req.body;

    const pool = await Pool.findById(poolId);
    if (!pool) return res.status(404).json({ message: 'Pool not found' });

    if (pool.status === 'completed')
      return res.status(400).json({ message: 'Pool is already completed' });

    // Block duplicate joins
    const existing = await Contribution.findOne({ user: req.user.id, pool: poolId });
    if (existing)
      return res.status(400).json({ message: 'You have already joined this pool' });

    const amount = pool.contributionAmount;

    // Create contribution — ticket auto-generated by pre('save') hook
    const contribution = new Contribution({
      user: req.user.id,
      pool: poolId,
      amount
    });
    await contribution.save();

    // Update pool total
    pool.totalContributed += amount;
    if (pool.totalContributed >= pool.targetAmount) {
      pool.status = 'completed';

      // 🆕 If instant mode, auto select winner immediately
      if (pool.winnerReleaseMode === 'instant') {
        const allContributions = await Contribution.find({ pool: pool._id });
        const randomIndex = Math.floor(Math.random() * allContributions.length);
        const winnerContribution = allContributions[randomIndex];
        pool.winner = winnerContribution.user;
        pool.winningTicket = winnerContribution.ticketCode;
        pool.winnerSelectedAt = new Date();
        pool.winnerPublished = true; // instant = publish immediately
      }
    }
    await pool.save();

    res.status(201).json({
      message: 'Successfully joined pool!',
      ticketCode: contribution.ticketCode, // 🆕 return ticket to user
      contribution,
      pool
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'Error joining pool' });
  }
});

// GET /api/contributions/my — logged in user's contributions
router.get('/my', auth, async (req, res) => {
  try {
    const contributions = await Contribution.find({ user: req.user.id })
      .populate('pool', 'title status targetAmount totalContributed contributionAmount winner winningTicket winnerPublished adminContact imageUrl images winnerReleaseMode scheduledReleaseTime')
      .sort({ createdAt: -1 });
    res.json(contributions);
  } catch (err) {
    res.status(500).json({ message: 'Error fetching your contributions' });
  }
});

// GET /api/contributions/pool/:poolId — all contributors for a pool
router.get('/pool/:poolId', async (req, res) => {
  try {
    const contributions = await Contribution.find({ pool: req.params.poolId })
      .populate('user', 'name email')
      .sort({ createdAt: -1 });
    res.json(contributions);
  } catch (err) {
    res.status(500).json({ message: 'Error fetching contributions' });
  }
});

module.exports = router;